export const base64Assets = () => {
    const assets = {
        images: {
            png: "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/wcAAwAB/WHOTmYAAAAASUVORK5CYII=",
            jpeg: "/9j/4AAQSkZJRgABAQEAAAAAAAD/2wCEAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQH/2wBDAREBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQH/wAARCADQAPoDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAf/xAAUEAEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIQAxAAAAFgAAAA//8QAFBEBAAAAAAAAAAAAAAAAAAAAIP/aAAgBAQABPwBj/8QAFBEBAAAAAAAAAAAAAAAAAAAAIP/aAAgBAgEBPwBj/8QAFBEBAAAAAAAAAAAAAAAAAAAAIP/aAAgBAwEBPwBj/9k",
            tiff: "SUkqAAwAAAAEAAcAAAEAAF0AAAABABgAAwAAAAEAAQAAAwAAgB0AAwAAAAEAAwAAAgAACkNyZWF0b3I6IFRJRkYgQ29udmVyc2lvbi4gDQAKICAg",
        }
    }
    return assets
}